<?php

/**
 * Role → permission slugs for BIBO ERM.
 * Super Admin bypasses all checks via Gate::before.
 *
 * Permission conventions: {module}.view | {module}.manage | {module}.approve
 */
return [

    'roles' => [
        'operations_manager' => [
            'analytics.view',
            'crm.view', 'crm.manage',
            'leads.view', 'leads.view_all', 'leads.create', 'leads.update', 'leads.delete', 'leads.convert', 'leads.assign',
            'contacts.view', 'contacts.view_all', 'contacts.create', 'contacts.update',
            'accounts.view', 'accounts.view_all', 'accounts.create', 'accounts.update',
            'deals.view', 'deals.view_all', 'deals.create', 'deals.update', 'deals.approve_discount',
            'deals.mark_won', 'deals.mark_lost', 'deals.create_project',
            'site_visits.view', 'site_visits.view_all', 'site_visits.schedule', 'site_visits.execute', 'site_visits.approve',
            'quotations.view', 'quotations.create', 'quotations.send', 'quotations.approve',
            'deal_payments.record', 'deal_payments.view',
            'activities.view', 'activities.view_all', 'activities.create', 'activities.complete',
            'field_day.view', 'field_day.create', 'field_day.manage',
            'projects.view', 'projects.manage', 'projects.view_all', 'projects.create', 'projects.update',
            'projects.assign_pm', 'projects.assign_engineers', 'projects.advance_stage', 'projects.advance_stage_warehouse', 'projects.advance_stage_production', 'projects.site_assessment_notes', 'projects.log_delay',
            'projects.update_timeline', 'projects.bom.view', 'projects.bom.upload', 'projects.bom.finalize',
            'projects.documents.view', 'projects.documents.upload', 'projects.addons.create',
            'projects.material_status.view', 'projects.floors.manage', 'projects.client_portal.view',
            'warehouse.view', 'warehouse.manage',
            'warehouse.stock.view', 'warehouse.stock.view_all',
            'warehouse.master_data.view', 'warehouse.master_data.manage',
            'warehouse.locations.view', 'warehouse.locations.manage',
            'warehouse.stock.adjust', 'warehouse.stock.transfer', 'warehouse.stock.receive', 'warehouse.stock.issue',
            'warehouse.reservations.view', 'warehouse.reservations.create', 'warehouse.reservations.release',
            'warehouse.aluminium.manage', 'warehouse.accessories.manage', 'warehouse.offcuts.manage',
            'warehouse.offcuts.log', 'warehouse.offcuts.allocate', 'warehouse.rubbers.manage',
            'warehouse.tools.view', 'warehouse.tools.manage', 'warehouse.tools.issue',
            'warehouse.stocktake.view', 'warehouse.stocktake.run',
            'procurement.view', 'procurement.manage', 'procurement.approve',
            'production.view', 'production.manage',
            'field_installation.view', 'field_installation.manage', 'field_installation.log',
            'field_installation.deliver', 'field_installation.tools',
            'production.view', 'production.manage', 'production.schedule.manage',
            'qc.view', 'qc.manage',
            'finance.view', 'finance.manage',
            'hr.view',
            'payroll.view',
        ],

        'sales_rep' => [
            'analytics.view',
            'crm.view', 'crm.manage',
            'leads.view', 'leads.create', 'leads.update', 'leads.convert', 'leads.assign',
            'contacts.view', 'contacts.create', 'contacts.update',
            'accounts.view', 'accounts.create', 'accounts.update',
            'deals.view', 'deals.create', 'deals.update', 'deals.mark_won', 'deals.mark_lost', 'deals.create_project',
            'site_visits.view', 'site_visits.schedule', 'site_visits.execute', 'site_visits.approve',
            'quotations.view', 'quotations.create', 'quotations.send',
            'deal_payments.record', 'deal_payments.view',
            'activities.view', 'activities.view_all', 'activities.create', 'activities.complete',
            'field_day.view', 'field_day.create',
            'projects.view', 'projects.create', 'projects.advance_stage_sales',
            'payroll.view',
        ],

        'field_officer' => [
            'crm.view', 'crm.manage',
            'leads.view', 'leads.create',
            'site_visits.view', 'site_visits.execute',
            'activities.view', 'activities.view_all', 'activities.create', 'activities.complete',
            'payroll.view',
        ],

        'project_manager' => [
            'analytics.view',
            'crm.view',
            'deals.view',
            'quotations.view', 'quotations.create', 'quotations.send',
            'accounts.view',
            'site_visits.view', 'site_visits.schedule', 'site_visits.approve',
            'projects.view', 'projects.manage', 'projects.update', 'projects.assign_pm',
            'projects.assign_engineers', 'projects.advance_stage', 'projects.site_assessment_notes', 'projects.log_delay',
            'projects.update_timeline', 'projects.bom.view', 'projects.bom.upload',
            'projects.bom.finalize', 'projects.documents.view', 'projects.documents.upload',
            'projects.addons.create', 'projects.material_status.view', 'projects.floors.manage',
            'warehouse.view',
            'procurement.view',
            'production.view',
            'field_installation.view',
            'qc.view',
            'finance.view',
            'payroll.view',
        ],

        'quotation_officer' => [
            'quotations.view', 'quotations.create', 'quotations.send', 'quotations.approve',
            'accounts.view',
            'projects.view',
            'site_visits.view',
            'payroll.view',
        ],

        'installation_lead' => [
            'field_installation.view', 'field_installation.manage', 'field_installation.log',
            'field_installation.deliver', 'field_installation.tools',
            'site_visits.view', 'site_visits.execute',
            'warehouse.tools.view', 'warehouse.tools.issue',
            'projects.view',
            'payroll.view',
        ],

        'field_installation_engineer' => [
            'field_installation.view', 'field_installation.log',
            'field_installation.deliver', 'field_installation.tools',
            'site_visits.view', 'site_visits.execute',
            'warehouse.tools.view', 'warehouse.tools.issue',
            'projects.view',
            'payroll.view',
        ],

        'production_manager' => [
            'analytics.view',
            'projects.view', 'projects.material_status.view', 'projects.site_assessment_notes',
            'projects.documents.view',
            'projects.advance_stage_production',
            'warehouse.stock.view',
            'warehouse.reservations.view',
            'warehouse.reservations.release',
            'production.view', 'production.manage', 'production.schedule.manage',
            'site_visits.view', 'site_visits.schedule', 'site_visits.execute',
            'qc.view',
            'payroll.view',
        ],

        'warehouse_manager_accessories' => [
            'warehouse.view', 'warehouse.manage',
            'warehouse.stock.view',
            'warehouse.master_data.view', 'warehouse.master_data.manage',
            'warehouse.locations.view', 'warehouse.locations.manage',
            'warehouse.stock.adjust', 'warehouse.stock.transfer', 'warehouse.stock.receive', 'warehouse.stock.issue',
            'warehouse.reservations.view',
            'warehouse.reservations.create',
            'warehouse.accessories.manage', 'warehouse.rubbers.manage',
            'warehouse.tools.view', 'warehouse.tools.manage', 'warehouse.tools.issue',
            'warehouse.stocktake.view', 'warehouse.stocktake.run',
            'procurement.view',
            'projects.view', 'projects.material_status.view', 'projects.advance_stage_warehouse',
            'payroll.view',
        ],

        'warehouse_manager_aluminium' => [
            'warehouse.view', 'warehouse.manage',
            'warehouse.stock.view',
            'warehouse.master_data.view', 'warehouse.master_data.manage',
            'warehouse.locations.view', 'warehouse.locations.manage',
            'warehouse.stock.adjust', 'warehouse.stock.transfer', 'warehouse.stock.receive', 'warehouse.stock.issue',
            'warehouse.reservations.view',
            'warehouse.reservations.create',
            'warehouse.aluminium.manage', 'warehouse.offcuts.manage', 'warehouse.offcuts.log', 'warehouse.offcuts.allocate',
            'warehouse.tools.view', 'warehouse.tools.manage', 'warehouse.tools.issue',
            'warehouse.stocktake.view', 'warehouse.stocktake.run',
            'procurement.view',
            'projects.view', 'projects.material_status.view', 'projects.advance_stage_warehouse',
            'payroll.view',
        ],

        'procurement_officer' => [
            'procurement.view', 'procurement.manage',
            'procurement.dashboard.view',
            'procurement.requisition.view', 'procurement.requisition.create',
            'procurement.requisition.update',
            'procurement.po.view', 'procurement.po.create', 'procurement.po.update', 'procurement.po.send',
            'procurement.grn.view', 'procurement.grn.create', 'procurement.grn.verify',
            'procurement.glass.view', 'procurement.glass.manage',
            'procurement.supplier.view', 'procurement.supplier.manage',
            'procurement.driver.view', 'procurement.driver.manage',
            'procurement.transport.manage',
            'procurement.delay.log',
            'procurement.watcher.manage',
            'warehouse.view',
            'warehouse.stock.view',
            'warehouse.locations.view',
            'projects.view', 'projects.material_status.view',
            'payroll.view',
        ],

        'qc_inspector' => [
            'qc.view', 'qc.manage',
            'production.view',
            'projects.view', 'projects.material_status.view', 'projects.documents.view',
            'payroll.view',
        ],

        'hr_manager' => [
            'hr.view', 'hr.manage',
            'employees.view', 'employees.create', 'employees.import', 'employees.update_hr_details', 'employees.approve',
            'users.invite', 'users.view', 'users.update_identity',
            'profile_changes.review',
            'leave.review', 'hr_requests.review', 'suggestions.review', 'hr_documents.manage',
            'payroll.view', 'payroll.manage',
        ],

        'finance_officer' => [
            'finance.view', 'finance.manage',
            'procurement.view',
            'projects.view', 'projects.material_status.view',
            'analytics.view',
            'payroll.view', 'payroll.approve',
        ],

        'it_admin' => [
            'it.manage',
            'users.manage',
            'users.invite',
            'users.view',
            'users.update',
            'users.suspend',
            'users.update_identity',
            'employees.view',
            'profile_changes.review',
            'devices.manage',
            'audit.view',
            'hr.view',
            'analytics.view',
            'crm.view',
            'payroll.view',
        ],

        'reception' => [
            'crm.view', 'crm.manage',
            'leads.view', 'leads.create', 'leads.update',
            'contacts.view', 'contacts.create',
            'accounts.view',
            'payroll.view',
        ],
    ],

    'policies' => [
        'lead' => ['view' => 'leads.view', 'create' => 'leads.create', 'manage' => 'leads.update'],
        'contact' => ['view' => 'contacts.view', 'create' => 'contacts.create', 'manage' => 'contacts.update'],
        'account' => ['view' => 'accounts.view', 'create' => 'accounts.create', 'manage' => 'accounts.update'],
        'deal' => ['view' => 'deals.view', 'create' => 'deals.create', 'manage' => 'deals.update'],
        'project' => ['view' => 'projects.view', 'manage' => 'projects.manage'],
        'warehouse_item' => ['view' => 'warehouse.stock.view', 'manage' => 'warehouse.master_data.manage'],
        'inventory_item' => ['view' => 'warehouse.stock.view', 'manage' => 'warehouse.manage'],
        'supplier' => ['view' => 'procurement.view', 'manage' => 'procurement.manage'],
        'driver' => ['view' => 'procurement.view', 'manage' => 'procurement.manage'],
        'purchase_requisition' => ['view' => 'procurement.view', 'manage' => 'procurement.manage'],
        'purchase_order' => [
            'view' => 'procurement.view',
            'create' => 'procurement.po.create',
            'manage' => 'procurement.manage',
            'approve' => 'procurement.approve',
        ],
        'goods_receipt' => ['view' => 'procurement.view', 'manage' => 'procurement.manage'],
        'glass_order' => ['view' => 'procurement.view', 'manage' => 'procurement.manage'],
        'transport_order' => ['view' => 'procurement.view', 'manage' => 'procurement.manage'],
        'procurement_delay' => ['view' => 'procurement.view', 'manage' => 'procurement.manage'],
        'procurement_watcher' => ['view' => 'procurement.view', 'manage' => 'procurement.manage'],
        'production_order' => ['view' => 'production.view', 'manage' => 'production.manage'],
        'qc_inspection' => ['view' => 'qc.view', 'manage' => 'qc.manage'],
        'qc_checklist_template' => ['view' => 'qc.view', 'manage' => 'qc.manage'],
        'qc_defect' => ['view' => 'qc.view', 'manage' => 'qc.manage'],
        'invoice' => ['view' => 'finance.view', 'manage' => 'finance.manage'],
        'payment' => ['view' => 'finance.view', 'manage' => 'finance.manage'],
        'expense' => ['view' => 'finance.view', 'manage' => 'finance.manage'],
        'user' => ['view' => 'users.view', 'manage' => 'users.manage'],
        'device' => ['view' => 'devices.manage', 'manage' => 'devices.manage'],
        'employee_profile' => ['view' => 'hr.view', 'manage' => 'hr.manage'],
        'role' => ['view' => 'users.view', 'manage' => 'users.manage'],
        'department' => ['view' => 'users.view', 'manage' => 'users.manage'],
        'audit_log' => ['view' => 'audit.view'],
        'field_installation_job' => [
            'view' => 'field_installation.view',
            'create' => 'field_installation.manage',
            'manage' => 'field_installation.manage',
        ],
    ],

];
